version: '3.9'

services:
  backend:
    image: ghcr.io/koyashiro/rdbms-playground-backend:latest
    environment:
      PLAYGROUND_NETWORK: ${PLAYGROUND_NETWORK:-playground-network}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 1323:1323

  frontend:
    image: ghcr.io/koyashiro/rdbms-playground-frontend:latest
    environment:
      API_HOST_URI: ${RDBMS_PLAYGROUND_API_HOST_URI}
    ports:
      - 3000:3000

networks:
  default:
    name: ${PLAYGROUND_NETWORK:-playground-network}
